name: Build and Test

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js environment
      uses: actions/setup-node@v1.4.2
    - run: rm -rf node_modules/
    - run: npm install
    - run: npm run build
    - run: npm run test
