name: Deploy
on:
    deployment

jobs:
    deployment:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Deployment pending
              uses: deliverybot/deployment-status@master
              with:
                  state: pending
                  token: "$"

            - name: Setup Node.js environment
              uses: actions/setup-node@v2

            - name: Install dependencies
              run: npm ci

            - name: Build
              run: npm run build

            - name: Bump version
              id: bump_version
              run: |
                  git config --global user.email action@github.com
                  git config --global user.name GitHub Action
                  npx standard-version --prerelease

            - name: Push bump artifacts
              run: git push --follow-tags

            - name: Setup NPM
              uses: actions/setup-node@v2
              with:
                  registry-url: "https://registry.npmjs.org'"
                  scope: "algotia"

            - name: Publish to NPM
              id: publish_npm
              run: npm publish
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Setup GPR
              uses: actions/setup-node@v2
              with:
                  registry-url: "https://npm.pkg.github.com/"
                  scope: "@algotia"

            - name: Publish to GPR
              id: publish_gpr
              run: npm publish
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: Deployment success
              if: success()
              uses: deliverybot/deployment-status@master
              with:
                  state: success
                  token: "$"

            - name: Deployment failure
              if: failure()
              uses: deliverybot/deployment-status@master
              with:
                  state: failure
                  token: "$"

