name: Publish to NPM

on:
  push:
    branches:
      - master
  pull_request:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js environment
      uses: actions.setup-node@v1.4.2
    - npm run publish

