name: Release

on:
  push:
    branches:
      - master

jobs:
  build_and_test:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Setup Node.js environment
      uses: actions/setup-node@v1.4.2
    - name: Install dependencies
      run: npm ci
    - name: Build
      run: npm run build
    - name: Test
      run: npm t
  release:
    name: Release
    needs: build_and_test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Bump version
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        npx standard-version --prerelease --skip.commit
    - name: Push bump artifacts
      run: git push --follow-tags
    - name: Install dependencies
      run: npm ci
    - name: Build
      run: npm run build
    - name: Setup Node.js with NPM
      uses: actions/setup-node@v1.4.2
      with:
        registry-url: 'https://registry.npmjs.org'
        scope: 'algotia'
    - name: Publish to NPM
      id: publish_npm
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    - name: Setup Node.js with GPR
      uses: actions/setup-node@v1.4.2
      with:
        registry-url: 'https://npm.pkg.github.com/'
        scope: '@algotia'
    - name: Publish to GPR
      id: publish_gpr
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Publish tag
      id: publish_tag
      run: |
        git push --follow-tags
        echo ::set-output name=tag_name::$(git describe HEAD --abbrev=0)
    - name: create release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        release_name: Release ${{ steps.publish_tag.outputs.tag_name }}
        tag_name: ${{ steps.publish_tag.outputs.tag_name }}
    

  #publish_npm: 
    #needs: build
    #runs-on: ubuntu-latest
    #steps:
    #- uses: actions/checkout@v2
    #- name: Setup Node.js environment
      #uses: actions/setup-node@v1.4.2
      #with:
        #registry-url: 'https://registry.npmjs.org'
        #scope: 'algotia'
    #- name: Download build artifacts
      #uses: actions/download-artifact@v1
      #with:
        #name: dist
    #- name: Publish to NPM
      #run: npm publish
      #env: 
        #NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
  
  #publish_gpr:
    #needs: build
    #runs-on: ubuntu-latest
    #steps:
    #- uses: actions/checkout@v2
    #- name: Setup Node.js environment
      #uses: actions/setup-node@v1.4.2
      #with:
        #registry-url: 'https://npm.pkg.github.com/'
        #scope: '@algotia'
    #- name: Download build artifacts
      #uses: actions/download-artifact@v1
      #with:
        #name: dist
    #- name: Publish to GPR
      #run: npm publish
      #env: 
        #NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
