name: Build and Test

on:
  pull_request:
    branches:
      - master
      - development

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]
        mongodb-version: [4.0]
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js environment
      uses: actions/setup-node@v1.4.2
    - name: Setup Redis
      run: |
          sudo apt-get install redis-server
          sudo systemctl start redis-server
    - name: Setup MongoDB
      uses: supercharge/mongodb-github-action@1.3.0
      with: 
        mongodb-version: ${{matrix.mongodb-version}}
    - name: Install dependencies
      run: npm ci
    - name: Build
      run: npm run build
    - name: Run tests
      run: npm t
